version: "3.9"
services:
  bee:
    build:
      context: ../../
      dockerfile: ./bee-node/docker/Dockerfile
      args:
        WITH_DASHBOARD: "true"
    image: bee
    stop_grace_period: 5m
    tty: true # for colored logs
    network_mode: host
    volumes:
      - ../config.toml:/bee_workdir/config.toml
      - ../storage:/bee_workdir/storage
