# We can get rid of this once Rust 1.58 lands
cargo-features = ["strip"]

[workspace]
members = [
	"bee-api/bee-rest-api",
	"bee-node",
	"bee-protocol",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[profile.min-size]
codegen-units = 1
inherits = "release"
lto = true
opt-level = "s"
panic = "abort"
strip = "symbols"
