name: Audit

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - mainnet
      - 'mainnet-develop*'
      - shimmer
      - 'shimmer-develop*'
    paths:
      - "**/Cargo.lock"
      - "**/Cargo.toml"
      - ".github/workflows/audit.yml"
      - ".cargo/config.toml"
  pull_request:
    branches:
      - mainnet
      - 'mainnet-develop*'
      - shimmer
      - 'shimmer-develop*'
    paths:
      - "**/Cargo.lock"
      - "**/Cargo.toml"
      - ".cargo/config.toml"

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
